/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import javax.swing.JOptionPane;

/**
 *
 * @author Equipo
 */

public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        txtpromedio = new javax.swing.JTextField();
        txtvalorsemestre = new javax.swing.JTextField();
        lblsubsidioveinte = new javax.swing.JLabel();
        lblsubsidiocuarenta = new javax.swing.JLabel();
        lblsubsidiosesenta = new javax.swing.JLabel();
        lblsubsidioochenta = new javax.swing.JLabel();
        lblsubsidiona = new javax.swing.JLabel();
        lblnumafiliados = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        btncalcular = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btncomenzar = new javax.swing.JButton();
        lbldineroveinte = new javax.swing.JLabel();
        lbldinerocuarenta = new javax.swing.JLabel();
        lbldinerosesenta = new javax.swing.JLabel();
        lbldineroochenta = new javax.swing.JLabel();
        lbldinerona = new javax.swing.JLabel();
        lblporcentajeveinte = new javax.swing.JLabel();
        lblporcentajecuarenta = new javax.swing.JLabel();
        lblporcentajesesenta = new javax.swing.JLabel();
        lblporcentajeochenta = new javax.swing.JLabel();
        lblporcentajena = new javax.swing.JLabel();
        lbltodo = new javax.swing.JLabel();
        btnmostrardatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("EJERCICIO");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("BENEFICIOS A ESTUDIANTES POR MEDIO DE UNA ONG");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Nombres:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Apellidos:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("Promedio:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("Valor semestre:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 0));
        jLabel6.setText("El total de estudiantes que obtuvieron subsidio");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("20%");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("40%");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("60%");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("80%");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("N/A");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 0));
        jLabel12.setText("Afiliados a la ONG");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 0));
        jLabel13.setText("El total de dinero otorgado en subsidio por la ONG");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("20%");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("40%");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("60%");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("80%");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("N/A");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 51, 0));
        jLabel19.setText("El porcentaje de estudiantes subsidiados acuerdo con el total de estudiantes  afiliados a la ONG");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("20%");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("40%");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("60%");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("80%");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("N/A");

        lblsubsidioveinte.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblsubsidioveinte.setText("-----");

        lblsubsidiocuarenta.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblsubsidiocuarenta.setText("-----");

        lblsubsidiosesenta.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblsubsidiosesenta.setText("-----");

        lblsubsidioochenta.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblsubsidioochenta.setText("-----");

        lblsubsidiona.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblsubsidiona.setText("-----");

        lblnumafiliados.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblnumafiliados.setText("-----");

        btnguardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btncalcular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncalcular.setText("Analizar");
        btncalcular.setEnabled(false);
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });

        btnsalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        btncomenzar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncomenzar.setText("Comenzar");
        btncomenzar.setEnabled(false);
        btncomenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomenzarActionPerformed(evt);
            }
        });

        lbldineroveinte.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbldineroveinte.setText("-----");

        lbldinerocuarenta.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbldinerocuarenta.setText("-----");

        lbldinerosesenta.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbldinerosesenta.setText("-----");

        lbldineroochenta.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbldineroochenta.setText("-----");

        lbldinerona.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbldinerona.setText("-----");

        lblporcentajeveinte.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblporcentajeveinte.setText("-----");

        lblporcentajecuarenta.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblporcentajecuarenta.setText("-----");

        lblporcentajesesenta.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblporcentajesesenta.setText("-----");

        lblporcentajeochenta.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblporcentajeochenta.setText("-----");

        lblporcentajena.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblporcentajena.setText("-----");

        lbltodo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltodo.setForeground(new java.awt.Color(255, 51, 0));
        lbltodo.setText("Analiza para ver la infomración");

        btnmostrardatos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnmostrardatos.setText("Mostrar Datos");
        btnmostrardatos.setEnabled(false);
        btnmostrardatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrardatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtvalorsemestre))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGap(26, 26, 26)
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtpromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btncomenzar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnsalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnguardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btncalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblnumafiliados))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7)
                                                .addComponent(lblsubsidioveinte))
                                            .addGap(35, 35, 35)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(lblsubsidiocuarenta))
                                            .addGap(42, 42, 42)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblsubsidiosesenta)
                                                .addComponent(jLabel9))
                                            .addGap(30, 30, 30)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblsubsidioochenta, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel11)
                                                .addComponent(lblsubsidiona)))
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(lbldineroveinte))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addGap(30, 30, 30)
                                                .addComponent(jLabel16)
                                                .addGap(30, 30, 30)
                                                .addComponent(jLabel17)
                                                .addGap(30, 30, 30)
                                                .addComponent(jLabel18))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lbldinerocuarenta)
                                                .addGap(36, 36, 36)
                                                .addComponent(lbldinerosesenta)
                                                .addGap(38, 38, 38)
                                                .addComponent(lbldineroochenta)
                                                .addGap(30, 30, 30)
                                                .addComponent(lbldinerona))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(lblporcentajeveinte))
                                        .addGap(46, 46, 46)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblporcentajecuarenta)
                                            .addComponent(jLabel21))
                                        .addGap(59, 59, 59)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblporcentajesesenta)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(jLabel22)))
                                        .addGap(55, 55, 55)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblporcentajeochenta)
                                            .addComponent(jLabel23))
                                        .addGap(53, 53, 53)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(lblporcentajena))
                                            .addComponent(jLabel24))))
                                .addGap(0, 122, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbltodo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnmostrardatos, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtpromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtvalorsemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsalir)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnguardar)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btncomenzar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsubsidioveinte)
                    .addComponent(lblsubsidiocuarenta)
                    .addComponent(lblsubsidiosesenta)
                    .addComponent(lblsubsidioochenta)
                    .addComponent(lblsubsidiona))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblnumafiliados))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldineroveinte)
                    .addComponent(lbldinerocuarenta)
                    .addComponent(lbldinerosesenta)
                    .addComponent(lbldineroochenta)
                    .addComponent(lbldinerona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblporcentajeveinte)
                    .addComponent(lblporcentajecuarenta)
                    .addComponent(lblporcentajesesenta)
                    .addComponent(lblporcentajeochenta)
                    .addComponent(lblporcentajena))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltodo)
                    .addComponent(btnmostrardatos))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int tamarray=3;
    int cantidad_estudiantes=1;
    int tempposicion=0;
    Estudiante[] objectName = new Estudiante[tamarray];
    
     /* AQUI UBICAMOS LAS VARIABLES */
        String nombres;
        String apellidos;
        Double promedio;
        Double valormatricula;
        Double dineroOchenta=0.0;
        Double dineroCuarenta=0.0;
        Double dineroSesenta=0.0;
        Double dineroVeinte=0.0;
        int subsidioochenta=0;
        int subsidiosesenta=0;
        int subsidiocuarenta=0;
        int subsidioveinte=0;
        int cantidadSubsidiados=0;
        int cantidadNoSubsidiados=0;
        
        /* AQUI TERMINA EL BLOQUE DE LAS VARIABLES */
    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        if (txtnombre.getText().length()==0 || txtapellidos.getText().length()==0 || txtpromedio.getText().length()==0 || txtvalorsemestre.getText().length()==0) {
            JOptionPane.showMessageDialog(null, "Por favor ingresa los datos faltantes.", "Importante",  JOptionPane.ERROR_MESSAGE);
        }else{
            Double temp;
        
        nombres=txtnombre.getText();
        apellidos=txtapellidos.getText();
        promedio=Double.parseDouble(this.txtpromedio.getText());
        valormatricula=Double.parseDouble(this.txtvalorsemestre.getText());
        if (promedio>3 && promedio<=3.5){
                temp=(valormatricula*20)/100;
                dineroVeinte= dineroVeinte+temp;
                subsidioveinte++;
                cantidadSubsidiados++;
            }else if (promedio>=3.6 && promedio<=3.9){
                temp=(valormatricula*40)/100;
                dineroCuarenta= dineroCuarenta+temp;
                subsidiocuarenta++;
                cantidadSubsidiados++;
            }else if (promedio>=4.0 && promedio<=4.5){
                temp=(valormatricula*60)/100;
                dineroSesenta= dineroSesenta+temp;
                subsidiosesenta++;
                cantidadSubsidiados++;
            }else if (promedio>=4.6 && promedio<=5.0){
                temp=(valormatricula*80)/100;
                dineroOchenta= dineroOchenta+temp;
                subsidioochenta++;
                cantidadSubsidiados++;
            }else{
                cantidadNoSubsidiados++;
            }
        
         objectName[tempposicion]=new Estudiante(nombres, apellidos, promedio, valormatricula);
               
           txtnombre.setText("");
           txtapellidos.setText("");
           txtpromedio.setText("");
           txtvalorsemestre.setText("");

           if (cantidad_estudiantes>=3) {
           btncalcular.setEnabled(true); 
           btnguardar.setEnabled(false);
           
           txtnombre.setEnabled(false);
           txtapellidos.setEnabled(false);
           txtpromedio.setEnabled(false);
           txtvalorsemestre.setEnabled(false);
          
           }
           
           cantidad_estudiantes++;   
           tempposicion++; 
        }
        
        
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i<objectName.length; i++){
            objectName[i].darSubsidio();
        }
        
        lblnumafiliados.setText(Integer.toString(cantidadSubsidiados));
        lblsubsidioveinte.setText(Integer.toString(subsidioveinte));
        lblsubsidiocuarenta.setText(Integer.toString(subsidiocuarenta));
        lblsubsidiosesenta.setText(Integer.toString(subsidiosesenta));
        lblsubsidioochenta.setText(Integer.toString(subsidioochenta));
        lblsubsidiona.setText(Integer.toString(tamarray-cantidadSubsidiados));
        lbldineroveinte.setText(Double.toString(dineroVeinte));
        lbldinerocuarenta.setText(Double.toString(dineroCuarenta));
        lbldinerosesenta.setText(Double.toString(dineroSesenta));
        lbldineroochenta.setText(Double.toString(dineroOchenta));
        lblporcentajeveinte.setText(Double.toString((subsidioveinte*100)/tamarray) + " %");
        lblporcentajecuarenta.setText(Double.toString((subsidiocuarenta*100)/tamarray) + " %");
        lblporcentajesesenta.setText(Double.toString((subsidiosesenta*100)/tamarray) + " %");
        lblporcentajeochenta.setText(Double.toString((subsidioochenta*100)/tamarray) + " %");
        lblporcentajena.setText(Double.toString(((tamarray-cantidadSubsidiados)*100)/tamarray) + " %");
        btncomenzar.setEnabled(true);
        btncalcular.setEnabled(false);
        btnmostrardatos.setEnabled(true);
        
        
         for (int i = 0; i<objectName.length; i++){           
           // System.out.println(objectName[i].dameDatos());
           lbltodo.setText((objectName[i].dameDatos()));
        }
         
        
        
        
    }//GEN-LAST:event_btncalcularActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btncomenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomenzarActionPerformed
        // TODO add your handling code here:
        btnguardar.setEnabled(true);
        btncomenzar.setEnabled(false);
        
    }//GEN-LAST:event_btncomenzarActionPerformed

    private void btnmostrardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrardatosActionPerformed
        // TODO add your handling code here:
        
        String informacion="";
        
        for (int i = 0; i < objectName.length; i++) {
            informacion+=objectName[i].getNombres()+ " " +objectName[i].getApellidos()+ " " +objectName[i].getPromedio()+ " " +objectName[i].getValormatricula()+"\n";
        }
        JOptionPane.showMessageDialog(null, informacion);
        btnmostrardatos.setEnabled(false);
    }//GEN-LAST:event_btnmostrardatosActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
       
        
        
        
        
        
        

//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcular;
    private javax.swing.JButton btncomenzar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmostrardatos;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbldinerocuarenta;
    private javax.swing.JLabel lbldinerona;
    private javax.swing.JLabel lbldineroochenta;
    private javax.swing.JLabel lbldinerosesenta;
    private javax.swing.JLabel lbldineroveinte;
    private javax.swing.JLabel lblnumafiliados;
    private javax.swing.JLabel lblporcentajecuarenta;
    private javax.swing.JLabel lblporcentajena;
    private javax.swing.JLabel lblporcentajeochenta;
    private javax.swing.JLabel lblporcentajesesenta;
    private javax.swing.JLabel lblporcentajeveinte;
    private javax.swing.JLabel lblsubsidiocuarenta;
    private javax.swing.JLabel lblsubsidiona;
    private javax.swing.JLabel lblsubsidioochenta;
    private javax.swing.JLabel lblsubsidiosesenta;
    private javax.swing.JLabel lblsubsidioveinte;
    private javax.swing.JLabel lbltodo;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtpromedio;
    private javax.swing.JTextField txtvalorsemestre;
    // End of variables declaration//GEN-END:variables
}
